version: '3.1'
services:
  stats-server:
    build: stats/stats-server/
    image: stats_server
    container_name: stats_server
    env_file:
      - .env
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=stats
      - SERVER_PORT=9090
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  ewm-service:
    build: main-service/
    image: main_service
    container_name: main_service
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - stats-server
      - ewm-db
    env_file:
      - .env
    environment:
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm
      - SERVER_PORT=8080
      - STATS_SERVER_PORT=9090
      - STATS_SERVER=stats-server
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
    container_name: ewm_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
