version: '3.1'
services:
  stats-client:
    build: stats/stats-client/
    image: stats_client
    container_name: stats_client
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - stats-server

  stats-server:
    build: stats/stats-server/
    image: stats_server
    container_name: stats_server
    env_file:
      - .env
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=stats
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
