DROP TABLE IF EXISTS endpoint_hits;

CREATE TABLE IF NOT EXISTS endpoint_hits (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR(100) NOT NULL,
    uri VARCHAR(100) NOT NULL,
    ip VARCHAR(15) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);
